pipeline {
  agent any

  environment {
    fileName = 'output.txt'
  }

  stages {
    stage('hello') {
      steps {
        echo 'hello world'
        writeFile(file: fileName, text: 'hello world')
      }
    }
    stage('archive artifacts') {
      steps {
        archiveArtifacts fileName
      }
    }
  }
}
