pipeline {
  agent any

  environment {
    fileName = 'output.json'
  }

  stages {
    stage('hello') {
      steps {
        script {
          def read_json = readJSON file: "jenkins/contents_list.json"
          def result = add_json_contents(read_json['list'])
          def output_json = "{'results': ${result}}"
          output_json = output_json.replace("[","{").replace("]","}")
          writeFile(file: fileName, text: output_json)
        }
      }
    }
    stage('archive artifacts') {
      steps {
        archiveArtifacts fileName
      }
    }
  }
  post {
    success {
      cleanWs()
    }
  }
}

def add_json_contents(contents) {
  def added_contents = [:]
  contents.each { key, value ->
    added_contents[key] = "{'result': ${value['value'].toString()}}"
  }
  return added_contents
}
